theme = "gruvbox-material"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# A-S-b = "ms*ms*"
# A-S-i = "ms*"
# A-S-t = "oi- [ ] "

[editor]
true-color = true
line-number = "relative"
mouse = false
scrolloff = 10
bufferline = "always"
shell = ["fish", "-c"]
# rainbow-brackets = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
