[[language]]
name = "markdown"
auto-format = true
indent = { tab-width = 4, unit = "    " }
file-types = [ "md" , { glob = "/var/folders/*" } ]
formatter = { command = "prettier" , args = ["--tab-width", "4" , "--parser" , "markdown"] }
