theme = "gruvbox_dark_soft"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor]
true-color = true
line-number = "relative"
mouse = false
rulers = [80]
scrolloff = 10
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
